services:
  quake3:
    image: docker.io/vkryvoruchko/quake3
    restart: always
    # host requires firewall-cmd
    network_mode: host
    volumes:
      - /opt/CampFitch/Quake3/baseq3:/usr/share/games/quake3/baseq3
      - ./quake3/server.cfg:/usr/share/games/quake3/baseq3/server.cfg

  tf2:
    image: docker.io/cm2network/tf2:latest-x64
    restart: always
    # host requires firewall-cmd
    network_mode: host
    volumes:
      - /opt/CampFitch/tf2:/home/steam/tf-dedicated:rw
      # /opt/CampFitch/tf2/tf/cfg/server.cfg
      - /opt/logs/games_tf2:/home/steam/Steam/logs:rw
    env_file:
      - /opt/CampFitch/secrets/games

  # Minecraft server (vanilla)
  mc:
    image: itzg/minecraft-server:latest
    networks:
      - minecraft
    ports:
      - 8912:25565
    environment:
      - EULA=TRUE
      - VERSION=1.21.5
    volumes:
      - /home/vince/Code/minecraft/worlds/1-mc:/data
    restart: unless-stopped

  # Minecraft Hardcore server
  minecraft:
    image: docker.io/itzg/minecraft-server:latest
    networks:
      - minecraft
    environment:
      - EULA=TRUE
      - VERSION=1.21.1
    volumes:
      - /home/vince/Code/minecraft/worlds/2-mchc:/data
    restart: unless-stopped

  # Minecraft router (multiplexes mc and mchc)
  router:
    image: itzg/mc-router:latest
    depends_on:
      - mc
      - mchc
    networks:
      - minecraft
      - container-dmz
    ports:
      - 25565:25565  # Port for Minecraft gameplay traffic
    environment:
      MAPPING: |
        mc.apps.halfblake.com=mc:25565
        mchc.apps.halfblake.com=mchc:25565
    labels:
      traefik.enable: true
      # Define HTTP routing for Traefik
      traefik.http.routers.minecraft.rule: HostRegexp(`{host:.+}`)
      traefik.http.routers.minecraft.entrypoints: websecure
      traefik.http.routers.minecraft.tls.certresolver: letsencrypt
      traefik.http.services.minecraft.loadbalancer.server.port: 25565
