services:
  quake3:
    image: docker.io/vkryvoruchko/quake3
    restart: always
    # host requires firewall-cmd
    network_mode: host
    #ports:
    #  - "10.0.0.10:27960:27960/udp"
    volumes:
      - /opt/CampFitch/Quake3/baseq3:/usr/share/games/quake3/baseq3
      - ./server.cfg:/usr/share/games/quake3/baseq3/server.cfg
