---
services:
  traefik:
    image: docker.io/library/traefik:v2.3
    command: --api.insecure=true --providers.docker
    ports:
      - ${ROUTER_BIND_ADDRESS}:80:80
      - ${ROUTER_BIND_ADDRESS}:443:443
    volumes:
      - ./traefik:/etc/traefik
      - /var/run/docker.sock:/var/run/docker.sock
      - /opt/logs/traefik:/var/log/traefik
      #- /opt/certs:/certs
    restart: always
    extra_hosts:
      - 'host.docker.internal:172.17.0.1'
    networks:
      - container-dmz
    secrets:
      - wildcard_cert
      - wildcard_key
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api.rule=Host(`traefik.apps.campcomputer.com`)"
      - "traefik.http.routers.api.service=api@internal"
      #- "traefik.http.routers.api.middlewares=api-auth"
      #- "traefik.http.middlewares.api-auth.basicauth.usersFile=/run/secrets/auth.db"

networks:
  container-dmz:
    external: true

secrets:
  wildcard_cert:
    file: /opt/CampFitch/secrets/wildcard_cert
  wildcard_key:
    file: /opt/CampFitch/secrets/wildcard_key
