---
services:
  traefik:
    image: docker.io/library/traefik:v3.6
    ports:
      - ${ROUTER_BIND_ADDRESS}:80:80
      - ${ROUTER_BIND_ADDRESS}:443:443
    volumes:
      - ./traefik:/etc/traefik
      - /var/run/docker.sock:/var/run/docker.sock
      - /opt/logs/traefik:/var/log/traefik
      - certs:/certs
    networks:
      - container-dmz
    restart: always
    extra_hosts:
      - 'host.docker.internal:172.17.0.1'
    env_file:
      - /opt/CampFitch/secrets/router.env

networks:
  container-dmz:
    external: true

volumes:
  certs:
