services:
  dns:
    image: lancachenet/lancache-dns:latest
    env_file: .env
    restart: unless-stopped
    ports:
      - ${DNS_BIND_IP}:53:53/udp
      - ${DNS_BIND_IP}:53:53/tcp
    volumes:
      - /opt/logs/lancache_dns:/var/log/named:rw
      - ./named.conf.options:/etc/bind/named.conf.options:rw

  monolithic:
    image: lancachenet/monolithic:latest
    env_file: .env
    restart: unless-stopped
    ports:
      - ${CACHE_BIND_IP}:80:80/tcp
      - ${CACHE_BIND_IP}:443:443/tcp
    volumes:
      - ${CACHE_ROOT}/cache:/data/cache
      - /opt/logs/lancache_monolithic:/data/logs:rw
