---
version: "2.1"
services:
  master:
    image: docker.io/puppet/puppetserver:6.14.1
    environment:
      - PUPPERWARE_ANALYTICS_ENABLED=false
      - PUPPETSERVER_HOSTNAME=puppet
      - DNS_ALT_NAMES=puppet.local,puppet.lab.campcomputer.com,puppet.campcomputer.com,puppet.boston.grantcohoe.com
      - AUTOSIGN=true
      - USE_PUPPETDB=false
    volumes:
      - /opt/puppet/ssl:/etc/puppetlabs/puppet/ssl
      - /opt/puppet/code:/etc/puppetlabs/code
      - ./r10k.yaml:/r10k.yaml:ro
      - ./fileserver.conf:/etc/puppetlabs/puppet/fileserver.conf:ro
      - /mnt/PuppetFS:/PuppetFS:ro
    ports:
      - 8140:8140
    restart: unless-stopped
