{
 "title": "Internet Connectivity",
 "description": "Overview of internet connectivity.",
 "tags": [
  "blackbox",
  "prometheus"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "interval",
    "label": "Interval",
    "query": "15s,30s,1m,2m,5m,10m,30m,1h,6h,12h,1d"
   },
   {
    "name": "target",
    "query": "label_values(probe_success, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "Perceived Internet Status",
   "type": "stat",
   "description": "Percentage of probe successes over the last minute.",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(quantile_over_time(.5, probe_success{job=~\"^internet_connectivity.*\"}[1m])) / count(probe_success{job=~\"^internet_connectivity.*\"})"
    }
   ]
  },
  {
   "title": "Probe Success Rate",
   "type": "stat",
   "description": "Real-time success rate of all probes.",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "(sum(probe_success{job=~\"^internet_connectivity.*\", instance=~\"$target\"})) / count(probe_success{job=~\"^internet_connectivity.*\", instance=~\"$target\"}) "
    }
   ]
  },
  {
   "title": "Latest Average Ping Time",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "avg(probe_duration_seconds{job=\"internet_connectivity__icmp\", instance=~\"$target\"})"
    }
   ]
  },
  {
   "title": "Latest Average DNS Resolution Time",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "avg(probe_dns_lookup_time_seconds{job=\"internet_connectivity__http_2xx\", instance=~\"$target\"})"
    }
   ]
  },
  { "title": "Global status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Median Probe Duration",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "quantile_over_time(.5, probe_duration_seconds{job=~\"^internet_connectivity.*\", instance=~\"$target\"}[$interval])",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Slow Probe Count",
   "type": "graph",
   "description": "Number of times in the interval that the median probe duration was longer than 1 second.",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "count(quantile_over_time(.5, probe_duration_seconds{job=~\"^internet_connectivity.*\", instance=~\"$target\"}[$interval]) >=1 )"
    }
   ]
  },
  {
   "title": "Median Ping Time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "quantile_over_time(.5, probe_duration_seconds{job=\"internet_connectivity__icmp\", instance=~\"$target\"}[$interval])",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Median DNS Resolution Time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "quantile_over_time(.5, probe_dns_lookup_time_seconds{job=\"internet_connectivity__http_2xx\", instance=~\"$target\"}[$interval])",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "$target status",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "repeat": "target",
   "collapsed": true,
   "panels": [
    {
     "title": "Status",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 4, "x": 0, "y": 15 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "probe_success{instance=~\"$target\"}"
      }
     ]
    },
    {
     "title": "HTTP Duration",
     "type": "graph",
     "gridPos": { "h": 6, "w": 10, "x": 4, "y": 15 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "probe_http_duration_seconds{instance=~\"$target\"}",
       "legendFormat": "{{ phase }}"
      }
     ]
    },
    {
     "title": "Probe Duration",
     "type": "graph",
     "gridPos": { "h": 6, "w": 10, "x": 14, "y": 15 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "probe_duration_seconds{instance=~\"$target\"}",
       "legendFormat": "seconds"
      }
     ]
    },
    {
     "title": "HTTP Status Code",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 4, "x": 0, "y": 17 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "probe_http_status_code{instance=~\"$target\"}"
      }
     ]
    },
    {
     "title": "HTTP Version",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 4, "x": 0, "y": 19 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "probe_http_version{instance=~\"$target\"}"
      }
     ]
    },
    {
     "title": "SSL",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 4, "x": 0, "y": 21 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "probe_http_ssl{instance=~\"$target\"}"
      }
     ]
    },
    {
     "title": "SSL Expiry",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 10, "x": 4, "y": 21 },
     "format": "dtdurations",
     "valueName": "current",
     "targets": [
      {
       "expr": "probe_ssl_earliest_cert_expiry{instance=~\"$target\"} - time()"
      }
     ]
    },
    {
     "title": "Average Probe Duration",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 5, "x": 14, "y": 21 },
     "format": "s",
     "valueName": "current",
     "targets": [
      {
       "expr": "avg(probe_duration_seconds{instance=~\"$target\"})"
      }
     ]
    },
    {
     "title": "Average DNS Lookup",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 5, "x": 19, "y": 21 },
     "format": "s",
     "valueName": "current",
     "targets": [
      {
       "expr": "avg(probe_dns_lookup_time_seconds{instance=~\"$target\"})"
      }
     ]
    }
   ]
  }
 ]
}