---
services:
  logs:
    image: docker.io/amir20/dozzle:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dozzle.rule=Host(`logs.apps.campcomputer.com`)"
    networks:
      - container-dmz

networks:
  backend:
  container-dmz:
    external: true

