---
version: '3.1'
services:
  unbound:
    image: docker.io/mvance/unbound:latest
    ports:
      - 172.17.0.1:53:53
      - 172.17.0.1:53:53/udp
    volumes:
      - ./unbound/unbound.conf:/opt/unbound/etc/unbound/unbound.conf:ro
      - ./unbound/adblock.conf:/opt/unbound/etc/unbound/adblock.conf:ro
      - ./unbound/lancache.conf:/opt/unbound/etc/unbound/lancache.conf:ro
    restart: always
