---
version: '3.1'
services:
  unbound:
    image: docker.io/mvance/unbound:latest
    ports:
      - 53:53
      - 53:53/udp
    volumes:
      - ./unbound/unbound.conf:/opt/unbound/etc/unbound/unbound.conf:ro
    restart: always
