---
version: '3.1'
services:
  unbound:
    image: docker.io/mvance/unbound:latest
    restart: always
    ports:
      - ${UNBOUND_BIND_ADDRESS}:53:53
      - ${UNBOUND_BIND_ADDRESS}:53:53/udp
    volumes:
      - ./unbound.conf:/opt/unbound/etc/unbound/unbound.conf:ro
      - ./adblock.conf:/opt/unbound/etc/unbound/adblock.conf:ro
    restart: always
