---
services:
  samba:
    image: docker.io/dockurr/samba
    container_name: storage-samba
    restart: unless-stopped
    network_mode: host
    volumes:
      - ./smb.conf:/etc/samba/smb.conf:ro
      - ./samba/users.conf:/etc/samba/users.conf:ro
      - samba-data:/var/lib/samba
      - /mnt:/mnt:rw
      - /etc/passwd:/etc/passwd:ro
      - /etc/group:/etc/group:ro

  web:
    image: docker.io/library/nginx:stable
    restart: unless-stopped
    volumes:
      - /mnt:/data:ro
      - ./nginx:/etc/nginx/conf.d:ro
    ports:
      - 10.0.0.175:80:80
      - 10.0.0.175:443:443
    networks:
      - container-dmz
    secrets:
      - wildcard_cert
      - wildcard_key
networks:
  container-dmz:
    external: true
volumes:
  samba-data:
secrets:
  wildcard_cert:
    file: /opt/CampFitch/secrets/wildcard_cert
  wildcard_key:
    file: /opt/CampFitch/secrets/wildcard_key
