---
version: "3.1"
services:
  netbootxyz:
    image: ghcr.io/netbootxyz/netbootxyz
    restart: unless-stopped
    environment:
      - MENU_VERSION=2.0.58
    ports:
      - 69:69/udp
    volumes:
      - config:/config:rw
      - assets:/assets:rw
    networks:
      - container-dmz
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.netboot.rule=Host(`netboot.apps.campcomputer.com`)"
      - "traefik.http.routers.netboot.service=netboot"
      - "traefik.http.services.netboot.loadbalancer.server.port=3000"
      - "traefik.http.routers.netbootassets.rule=Host(`netboot-assets.apps.campcomputer.com`)"
      - "traefik.http.routers.netbootassets.service=netbootassets"
      - "traefik.http.services.netbootassets.loadbalancer.server.port=80"
volumes:
  assets:
  config:
networks:
  container-dmz:
    external: true
