---
version: "3.1"
services:
  netbootxyz:
    image: ghcr.io/netbootxyz/netbootxyz
    restart: unless-stopped
    environment:
      - MENU_VERSION=2.0.58
      - TFTPD_OPTS=--create
    ports:
      - 69:69/udp
    volumes:
      - config:/config:rw
      - /opt/CampFitch/TurboPXE:/config/menus/local:rw
      - assets:/assets:rw
      - backups:/config/menus/backups:rw
    networks:
      - container-dmz
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.netboot.rule=Host(`netboot.apps.campcomputer.com`)"
      - "traefik.http.routers.netboot.service=netboot"
      - "traefik.http.services.netboot.loadbalancer.server.port=3000"
      - "traefik.http.routers.netbootassets.rule=Host(`netboot-assets.apps.campcomputer.com`)"
      - "traefik.http.routers.netbootassets.service=netbootassets"
      - "traefik.http.services.netbootassets.loadbalancer.server.port=80"
    depends_on:
      init-netbootxyz:
        condition: service_completed_successfully
  init-netbootxyz:
    image: ghcr.io/netbootxyz/netbootxyz
    command: find /config/menus/local/ \( -name "*.ipxe" -or -name "*.cfg" \) -exec echo "Installing {}." \; -exec cp -f {} /config/menus/ \;
    volumes:
      - config:/config:rw
      - /opt/CampFitch/TurboPXE:/config/menus/local:rw
volumes:
  assets:
  config:
  backups:
networks:
  container-dmz:
    external: true
