tls:
  options:
    default:
      maxVersion: VersionTLS13
  stores:
    default:
      defaultGeneratedCert:
        resolver: namecheap
        domain:
          main: apps.campcomputer.com
          sans:
            - "*.apps.campcomputer.com"
            - "*.lab.campcomputer.com"
http:
  routers:
    dashboard:
      rule: Host(`traefik.apps.campcomputer.com`) && (PathPrefix(`/api`) || PathPrefix(`/dashboard`))
      service: api@internal
