; Allow HTTP file uploads
file_uploads = On
; Amount of memory a script can allocate
memory_limit = 256M
; Max upload file size
upload_max_filesize = 30M
; Max size of POST request (must be bigger than upload_max_filesize)
post_max_size = 32M
; Runtime of a script before termination
max_execution_time = 60
