<?php
# This file was automatically generated by the MediaWiki 1.38.2
# installer. If you make manual changes, please keep track in case you
# need to recreate them later.
#
# See docs/Configuration.md for all configurable settings
# and their default values, but don't forget to make changes in _this_
# file, not there.
#
# Further documentation for configuration settings may be found at:
# https://www.mediawiki.org/wiki/Manual:Configuration_settings

# Protect against web entry
if ( !defined( 'MEDIAWIKI' ) ) {
	exit;
}


## Uncomment this to disable output compression
# $wgDisableOutputCompression = true;

$wgSitename = "Fitchipedia";

## The URL base path to the directory containing the wiki;
## defaults for all runtime URL paths are based off of this.
## For more information on customizing the URLs
## (like /w/index.php/Page_title to /wiki/Page_title) please see:
## https://www.mediawiki.org/wiki/Manual:Short_URL
$wgScriptPath = "";
$wgArticlePath = '/wiki/$1';

## The protocol and server name to use in fully-qualified URLs
$wgServer = $_ENV["MW_WGSERVER"];

## The URL path to static resources (images, scripts, etc.)
$wgResourceBasePath = $wgScriptPath;

## The URL paths to the logo.  Make sure you change this from the default,
## or else you'll overwrite your logo when you upgrade!
#$wgLogos = [
	#'1x' => "$wgResourceBasePath/resources/assets/change-your-logo.svg",
  #'svg' => "/images/c/c7/Ymca.svg",
#  '1x' => "${wgUploadPath}/images/2/27/Fitchipedia_logo.png",
  #'icon' => "/images/2/27/Fitchipedia_logo.png",
#];

#$wgLogo = "$wgScriptPath/images/2/27/Fitchipedia_logo.png";
#$wgLogos = [
#  '1x' => "https://fitchipedia.apps.grantcohoe.com/images/2/27/Fitchipedia_logo.png",
#  '1.5x' => "https://fitchipedia.apps.grantcohoe.com/images/2/27/Fitchipedia_logo.png",
#  '2x' => "https://fitchipedia.apps.grantcohoe.com/images/2/27/Fitchipedia_logo.png",
#];
$wgLogos = [
  'icon' => "/images/0/01/Fitchipedia_Logo.png",
  'wordmark' => [
    'src' => "/images/4/44/Fitchipedia_wordmark.png",
    'width' => 155,
    'height' => 45,
  ],
];

## UPO means: this is also a user preference option

$wgEnableEmail = true;
$wgEnableUserEmail = false; # UPO
$wgNoReplyAddress = "noreply@campfitchymca.org";
$wgSMTP = [
    'host'     => 'tls://smtp-relay.gmail.com',
    'IDHost'   => 'fitchipedia.org',      // Generally this will be the domain name of your website (aka mywiki.org)
    'port'     => 465,                // Port to use when connecting to the SMTP server
    'auth'     => false,               // Should we use SMTP authentication (true or false)
    'localhost' => 'fitchipedia.org', // EHLO
];
$wgEmailConfirmToEdit = true;

$wgEmergencyContact = "grantcohoe@campfitchymca.org";
$wgPasswordSender = "noreply@campfitchymca.org";

$wgEnotifUserTalk = true; # UPO
$wgEnotifWatchlist = true; # UPO
$wgEmailAuthentication = true;

## Database settings
$wgDBtype = "mysql";
$wgDBserver = "database";
$wgDBname = $_ENV["MYSQL_DATABASE"];
$wgDBuser = $_ENV["MYSQL_USER"];
$wgDBpassword = $_ENV["MYSQL_PASSWORD"];

# MySQL specific settings
$wgDBprefix = "";

# MySQL table options to use during installation or update
$wgDBTableOptions = "ENGINE=InnoDB, DEFAULT CHARSET=binary";

# Shared database table
# This has no effect unless $wgSharedDB is also set.
$wgSharedTables[] = "actor";

## Shared memory settings
$wgMainCacheType = CACHE_ACCEL;
$wgMemCachedServers = [];

## To enable image uploads, make sure the 'images' directory
## is writable, then set this to true:
$wgEnableUploads = true;
$wgUseImageMagick = true;
$wgImageMagickConvertCommand = "/usr/bin/convert";

# InstantCommons allows wiki to use images from https://commons.wikimedia.org
$wgUseInstantCommons = false;

# Periodically send a pingback to https://www.mediawiki.org/ with basic data
# about this MediaWiki instance. The Wikimedia Foundation shares this data
# with MediaWiki developers to help guide future development efforts.
$wgPingback = false;

# Site language code, should be one of the list in ./languages/data/Names.php
$wgLanguageCode = "en";

# Time zone
$wgLocaltimezone = "UTC";

## Set $wgCacheDirectory to a writable directory on the web server
## to make your wiki go slightly faster. The directory should not
## be publicly accessible from the web.
#$wgCacheDirectory = "$IP/cache";

$wgSecretKey = $_ENV["MW_WGSECRETKEY"];

# Changing this will log out all existing sessions.
$wgAuthenticationTokenVersion = "1";

# Site upgrade key. Must be set to a string (default provided) to turn on the
# web installer while LocalSettings.php is in place
$wgUpgradeKey = $_ENV["MW_WGUPGRADEKEY"];

## For attaching licensing metadata to pages, and displaying an
## appropriate copyright notice / icon. GNU Free Documentation
## License and Creative Commons licenses are supported so far.
$wgRightsPage = "Copyrights"; # Set to the title of a wiki page that describes your license/copyright
$wgRightsUrl = "";
$wgRightsText = "";
$wgRightsIcon = "";

# Path to the GNU diff3 utility. Used for conflict resolution.
$wgDiff3 = "/usr/bin/diff3";

## Default skin: you can change the default skin. Use the internal symbolic
## names, e.g. 'vector' or 'monobook':
$wgDefaultSkin = "vector-2022";
$wgDefaultMobileSkin = 'minerva';

# Enabled skins.
# The following skins were automatically enabled:
wfLoadSkin( 'Timeless' );
wfLoadSkin( 'Vector' );
wfLoadSkin( 'MinervaNeue' );

# https://www.mediawiki.org/wiki/Skin:Vector/2022#Configuration
$wgVectorNightMode['beta'] = true;
$wgVectorNightMode['logged_out'] = true;
$wgVectorNightMode['logged_in'] = true;
$wgDefaultUserOptions['vector-theme'] = 'os';


# Enabled extensions. Most of the extensions are enabled by adding
# wfLoadExtension( 'ExtensionName' );
# to LocalSettings.php. Check specific extension documentation for more details.
# The following extensions were automatically enabled:
wfLoadExtension( 'CategoryTree' );
wfLoadExtension( 'CiteThisPage' );
wfLoadExtension( 'CodeEditor' );
#wfLoadExtension( 'Interwiki' ); # Merged into Core 1.44
wfLoadExtension( 'PdfHandler' );
wfLoadExtension( 'SyntaxHighlight_GeSHi' );
wfLoadExtension( 'VisualEditor' );
wfLoadExtension( 'WikiEditor' );
wfLoadExtension( 'MultiBoilerplate' );
wfLoadExtension( 'PortableInfobox' );
wfLoadExtension( 'PageImages' );
wfLoadExtension( 'ParserFunctions' );
wfLoadExtension( 'Cite' );
wfLoadExtension( 'Linter' );
wfLoadExtension( 'DiscussionTools' );
wfLoadExtension( 'MobileFrontend' );



# End of automatically generated settings.
# Add more configuration options below.

# https://www.mediawiki.org/wiki/Manual:$wgUsePrivateIPs
$wgUsePrivateIPs = true;
$wgCdnServersNoPurge = array( '172.19.0.2', '172.19.0.3', '172.19.0.4', '172.19.0.5', '172.19.0.6', '172.19.0.7', '172.19.0.8', '172.19.0.9', '172.19.0.10' );
# https://www.mediawiki.org/wiki/Manual:Timezone
$wgLocaltimezone = "America/New_York";
date_default_timezone_set( $wgLocaltimezone );

# https://www.mediawiki.org/wiki/Manual:$wgFileExtensions
$wgFileExtensions = [ 'png', 'gif', 'jpg', 'jpeg', 'webp', 'svg', 'pdf' ];

# https://www.mediawiki.org/wiki/Extension:MultiBoilerplate#Configuration
$wgMultiBoilerplateOptions[ "My Boilerplate" ] = "Template:My Boilerplate";

# Debug
#$wgShowExceptionDetails = true;
#$wgShowSQLErrors = true;
#$wgDebugToolbar = true;
#$wgDevelopmentWarnings = true;
#error_reporting( -1 );
#ini_set( 'display_errors', 1 );
# Needed for Discussion Tools
$wgFragmentMode = ["html5"];

$wgVisualEditorAvailableNamespaces = [
  'Fitchipedia' => true,
];

# Cloudflare Turnstyle CAPTCHA
wfLoadExtensions([ 'ConfirmEdit', 'ConfirmEdit/Turnstile' ]);
$wgCaptchaClass = MediaWiki\Extension\ConfirmEdit\Turnstile\Turnstile::class;

$wgTurnstileSiteKey= getenv( 'CF_SITE_KEY' ) ?: '';
$wgTurnstileSecretKey= getenv( 'CF_SECRET_KEY' ) ?: '';

# Search the fitchipedia namespace as well as the main namespace.
$wgNamespacesToBeSearchedDefault[NS_PROJECT] = true;
