---
services:
  controller:
    image: ghcr.io/linuxserver/unifi-controller:latest
    #container_name: unifi-controller
    environment:
      - PUID=1000
      - PGID=1000
      #- MEM_LIMIT=1024M #optional
    volumes:
      - /opt/unifi:/config
    network_mode: host
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.unifi.rule=Host(`unifi.lab.campcomputer.com`,`unifi.apps.campcomputer.com`)"
      - "traefik.http.services.unifi.loadbalancer.server.port=8443"
      - "traefik.http.services.unifi.loadbalancer.server.scheme=https"
      #- "traefik.http.middlewares.unifi.redirectregex.regex=^http://unifi.lab.campcomputer.com/(.*)"
      #- "traefik.http.middlewares.unifi.redirectregex.replacement=http://unifi.lab.campcomputer.com:8080/$${1}"
      #- "traefik.http.routers.unifi.middlewares=unifi@docker"
