---
version: "2.1"
services:
  controller:
    image: ghcr.io/linuxserver/unifi-controller
    #container_name: unifi-controller
    environment:
      - PUID=1000
      - PGID=1000
      - MEM_LIMIT=1024M #optional
    volumes:
      - /opt/unifi:/config
    network_mode: host
#    networks:
#      - container-dmz
#    ports:
#      - ${UNIFI_BIND_IP}:3478:3478/udp
#      - ${UNIFI_BIND_IP}:10001:10001/udp
#      - ${UNIFI_BIND_IP}:8080:8080
#      - ${UNIFI_BIND_IP}:8443:8443
#      - ${UNIFI_BIND_IP}:1900:1900/udp #optional
#      - ${UNIFI_BIND_IP}:8843:8843 #optional
#      - ${UNIFI_BIND_IP}:8880:8880 #optional
#      - ${UNIFI_BIND_IP}:6789:6789 #optional
#      - ${UNIFI_BIND_IP}:5514:5514/udp #optional
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.unifi.rule=Host(`unifi.lab.campcomputer.com`,`unifi.apps.campcomputer.com`)"
      - "traefik.http.services.unifi.loadbalancer.server.port=8443"
      - "traefik.http.services.unifi.loadbalancer.server.scheme=https"
      #- "traefik.http.middlewares.unifi.redirectregex.regex=^http://unifi.lab.campcomputer.com/(.*)"
      #- "traefik.http.middlewares.unifi.redirectregex.replacement=http://unifi.lab.campcomputer.com:8080/$${1}"
      #- "traefik.http.routers.unifi.middlewares=unifi@docker"

networks:
  container-dmz:
    external: true
