---
version: '3.1'
services:
  nginx:
    image: docker.io/library/nginx:stable
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.revproxy.rule=Host(`photos.campcomputer.com`,`photos.apps.campcomputer.com`)"
    volumes:
      - ./nginx:/etc/nginx/conf.d:ro
    networks:
      - container-dmz
    restart: always

networks:
  container-dmz:
    external: true
