---
version: '2'
services:
  prometheus:
    image: docker.io/bitnami/prometheus:2.33.5
    volumes:
      - prometheus:/opt/bitnami/prometheus/data
      - ./prometheus/prometheus.yml:/opt/bitnami/prometheus/conf/prometheus.yml
    command:
      - '--web.enable-admin-api'
      - '--storage.tsdb.retention.time=400d'
      - '--config.file=/opt/bitnami/prometheus/conf/prometheus.yml'
    restart: always
    networks:
      - container-dmz
      - backend
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.prometheus.rule=Host(`prometheus.apps.campcomputer.com`)"

  grafana:
    image: docker.io/grafana/grafana:8.4.4
    volumes:
      - grafana:/var/lib/grafana:rw
      - ./grafana/datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yaml:ro
      - ./grafana/dashboards.yaml:/etc/grafana/provisioning/dashboards/dashboards.yaml:ro
      - ./grafana/grafana.ini:/etc/grafana/grafana.ini:ro
      - ./grafana/dashboards:/etc/dashboards:ro
    depends_on:
      - prometheus
    environment:
      GF_INSTALL_PLUGINS: 'grafana-piechart-panel'
    restart: always
    networks:
      - container-dmz
      - backend
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.grafana.rule=Host(`grafana.apps.campcomputer.com`)"

  blackbox:
    # https://github.com/prometheus/blackbox_exporter/blob/master/README.md
    # https://www.robustperception.io/icmp-pings-with-the-blackbox-exporter
    image: docker.io/prom/blackbox-exporter:v0.20.0
    command: '--config.file=/config/blackbox.yml'
    volumes:
      - ./blackbox/blackbox.yml:/config/blackbox.yml
    restart: always
    cap_add:
      - NET_RAW
    networks:
      - container-dmz
      - backend
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.blackbox.rule=Host(`blackbox.apps.campcomputer.com`)"

  iperf:
    image: docker.io/networkstatic/iperf3:latest
    command: '-s'
    ports:
      - 5201:5201

volumes:
  grafana:
  prometheus:

networks:
  backend:
    external: false
  container-dmz:
    external: true
